version: "3.3"
services:
  node-master:
    depends_on:
      - node-slave1
      - node-slave2
    build: .
    container_name: node-master
    hostname: node-master
    tty: true
    ports:
      - "8088:8088"
      - "50070:50070"
      - "50030:50030"
      - "8080:8080"
      - "8042:8042"
      - "8888:8888"
      - "4040:4040"
      - "2222:22"
    volumes:
      - ./pyspark:/root/lab/pyspark
    
  node-slave1:
    build: .
    container_name: node-slave1
    hostname: node-slave1
    tty: true
    ports:
      - "7042:8042"
    
  node-slave2:
    build: .
    container_name: node-slave2
    hostname: node-slave2
    tty: true
    ports:
      - "9042:8042"
    